version: '3.5'

services:

  Rehber.Api:
    image: rehber.api       
    build:
      context: ./Services/Rehber.Api
      dockerfile: Dockerfile.debug
    ports: 
    - "8081:80"
    volumes: 
      - ./Services/Rehber.Api/bin/pub/:/app
    container_name: Rehber.Api
    depends_on:
      - database

  Rapor.Api:
    image: rapor.api
    build:
      context: ./Services/Rapor.Api
      dockerfile: Dockerfile.debug
    ports: 
    - "8084:80"
    volumes: 
      - ./Services/Rapor.Api/bin/pub/:/app
    container_name: Rapor.Api   
    depends_on:
      - database
     
  database:
    image: "postgres" 
    ports:
      - 5432:5432
    env_file:
      - ./Database/database.env 
    volumes:
      - database-data:/var/lib/postgresql/data/ 
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@umut.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "database:pgsql-server" 
volumes:
  database-data: 
  pgadmin-data: 
