FROM mcr.microsoft.com/dotnet/aspnet:5.0
RUN mkdir app

#Install debugger
RUN apt-get update
RUN apt-get install curl -y unzip
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

EXPOSE 80/tcp

#Keep the debugger container on
WORKDIR /app
ENTRYPOINT ["dotnet", "Rapor.Api.dll"]
